### ISSUE TITLE
Pi Stuff

### ISSUE THREAD

**Issue by dianecw** [dianecw/adshirtise#14]
- [x] Parsing 32x32 -> Web will pass an array of colors.
- [x] Preset Images?
- [x] Starting matrix from python (Bash script)

**Comment by radiolarian** [comment]
currently correctly parses text from server (thanks michelle!) just gotta implement images now

**Comment by radiolarian** [comment]
new todo:
[] fix the effing flickering
[] get cool demos

**Comment by radiolarian** [comment]
new todo
- [x] fix frikkn flickering
- [x] cool demos
